### ISSUE TITLE
Unable to use locale after toCalendarSystem

### ISSUE THREAD

**Issue by hmmftg** [calidy-com/dayjs-calendarsystems#2]
Hi, we can not call locale after `toCalendarSystem` like this: 

```js
dayjs(dt)
  .toCalendarSystem("persian")
  .locale("fa")
  .format("dddd DD MMMM YYYY")
``` 
it return's this error:
```
caught RangeError: Maximum call stack size exceeded
    at m2.valueOf (dayjs.min.js:1:3172)
    at m2.toDate (dayjs.min.js:1:6641)
    at proto.clone (jalaliday.esm.js:525:25)
    at e2.toCalendarSystem (dayjs-calendarsystems.esm.min.js:35:4657)
    at e2.init (dayjs-calendarsystems.esm.min.js:35:1463)
    at proto.init (jalaliday.esm.js:236:22)
    at m2.parse (dayjs.min.js:1:2558)
    at proto.parse (jalaliday.esm.js:259:30)
    at new M2 (dayjs.min.js:1:2071)
    at O (dayjs.min.js:1:1902)
m
```
and without `locale` we get `'Monday 14 Esfand 1402'` instead of `'دوشنبه 14 اسفند 1402'`

**Comment by amirhmoradi** [comment]
Hi @hmmftg , thanks for using the plugin.
I see in the error log you shared that you seem to be using "jalaliday.esm.js" in combination with my plugin. This might be the main cause of the error as my plugin is a replacement of all other calendar converters.

As you can see in the unit tests ( here: https://github.com/calidy-com/dayjs-calendarsystems/blob/main/test/format.test.js ), the usage of `locale` and `format` are correctly taken care of in the plugin.

Please make sure to follow the instruction in the `Usage` section on the [README.md](https://github.com/calidy-com/dayjs-calendarsystems/blob/main/README.md) file.

Here is a working code:
```js
import dayjs from "dayjs";
import "dayjs/locale/fa";

import calendarSystems from "@calidy/dayjs-calendarsystems";
import PersianCalendarSystem from "@calidy/dayjs-calendarsystems/calendarSystems/PersianCalendarSystem";

dayjs.extend(calendarSystems);
dayjs.registerCalendarSystem("persian", new PersianCalendarSystem());

const dt = dayjs("2023-05-14");

const myDate = dt.toCalendarSystem("persian").locale("fa").format("dddd DD MMMM YYYY");
```

I will close this issue, please comment with details and more info if you believe this should be kept open.

Best regards :)
