### ISSUE TITLE
Is Amazigh Calendar correct

### ISSUE THREAD

**Issue by abdelhaqueidali** [calidy-com/dayjs-calendarsystems#6]
I could not get the plug in to run on my device. So I have a question, when Amazigh date is 1 Yennayer, is it corresponding to 14th January for the Gregorian calendar cause:
14th January is the first day in the new Amazigh year, so it corresponds to 1 Yennayer. 11th being the current day in some repositories and codes on GitHub is actually wrong because of many circumstances. In case of having it here as well.
If you would not like to change it, maybe creating another version that follows that, since that is how it's in Morocco and Libya Algeria got it mixed up because of many issues. From 12th being the first day, to moving it to 11th, but actually 14th is what is common in sources I have seen before. 
Tawalt (Libya) :
https://tawalt.tinussan.com/%d8%a3%d9%86%d8%aa-%d9%84%d9%8a%d8%a8%d9%8a-%d8%a5%d8%b0%d8%a7-%d8%a3%d9%86%d8%aa-%d8%a3%d9%85%d8%a7%d8%b2%d9%8a%d8%ba%d9%8a/#more-843

From Wikipedia:
 "The length of the year and of the individual months is the same as in the Julian calendar: three years of 365 days followed by a leap year of 366, without exceptions, and 30- and 31-day months, except for the second one that has 28 days. The only slight discrepancy lies in that the extra day in leap years is not usually added at the end of February, but at the end of the year. This means that the beginning of the year (the first day of yennayer) corresponds to the 14th day of January in the Gregorian calendar, which coincides with the offset accumulated during the centuries between astronomical dates and the Julian calendar."
![Yennayer](https://github.com/user-attachments/assets/7a5ced78-43bd-4a8a-9d9c-b0e854930389)
"A page from a **Tunisian** calendar, showing the correspondence of 1 Yennayer ʿajmi (in red on bottom) with 14 January of the Gregorian calendar. The writing on the bottom signals that it is ʿajmi New Year's Day and that al-lyali al-sud ("the black nights") are beginning."

https://en.m.wikipedia.org/wiki/Berber_calendar

**Comment by amirhmoradi** [comment]
@abdelhaqueidali  hi and thanks for your interest. I have based this version on the 14th Jan, see here: https://github.com/calidy-com/dayjs-calendarsystems/blob/99a60a1a8283208773310cc89af193bc8d268908/src/calendarSystems/AmazighCalendarSystem.js#L71

I based this decision on lots of research on the amazigh calendar (wikipedia, the amazigh association, population concerned about the calendar).

Please read the documentation in the README.md file and try the plugin. If you have a suggestion to change the current version or provide a new version for other countries/users, please open a PR and I will gladly review and comment on it until we get an acceptable solution.

Best regards.

**Comment by abdelhaqueidali** [comment]
If it has january 14th as the first day of Amazigh year, then there is no issue. Just saw that on some github repositories mistakenly use 11th or 12th of january as the first day of the new year.
